-- 날짜가 더 빠르다 = 대소비교 시 더 작다

SELECT
    ANIMAL_OUTS.ANIMAL_ID,
    ANIMAL_OUTS.NAME
FROM(
    ANIMAL_INS INNER JOIN ANIMAL_OUTS 
    ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    )
WHERE
    ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY
    ANIMAL_INS.DATETIME;
